export const DISPLAY_ALERT = 'DISPLAY_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const LOGOUT_USER = 'LOGOUT_USER';
export const HANDLE_JOB_CHANGE = 'HANDLE_JOB_CHANGE';
export const CLEAR_JOB_VALUES = 'CLEAR_JOB_VALUES';

export const CREATE_JOB_BEGIN = 'CREATE_JOB_BEGIN';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR';


export const GET_JOBS_BEGIN = 'GET_JOBS_BEGIN';
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';

export const EDIT_JOB = 'EDIT_JOB';

export const DELETE_JOB_BEGIN = 'DELETE_JOB_BEGIN';

export const SH0W_STATS_BEGIN = 'SHOW_STATS_BEGIN';
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS';

export const SET_SEARCH = 'SET_SEARCH';
export const CLEAR_SEARCH_VALUES = 'CLEAR_SEARCH_VALUES';

export const UPDATE_PAGE = 'UPDATE_PAGE';